-- MySQL Script generated by MySQL Workbench
-- Mon Mar 26 14:03:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProjetS2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProjetS2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProjetS2` DEFAULT CHARACTER SET utf8 ;
USE `ProjetS2` ;

-- -----------------------------------------------------
-- Table `ProjetS2`.`Adoptant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetS2`.`Adoptant` (
  `id_adoptant` INT NOT NULL AUTO_INCREMENT,
  `nom_ado` TEXT(50) NOT NULL,
  `prenom_ado` TEXT(40) NOT NULL,
  `pays_ado` TEXT(50) NOT NULL,
  `ville_ado` VARCHAR(50) NOT NULL,
  `tel_ado` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_adoptant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetS2`.`Refuge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetS2`.`Refuge` (
  `id_refuge` INT NOT NULL AUTO_INCREMENT,
  `vill_ref` TEXT(50) NOT NULL,
  `tel_ref` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_refuge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetS2`.`Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetS2`.`Animal` (
  `id_animal` INT NOT NULL AUTO_INCREMENT,
  `nom_ani` VARCHAR(40) NOT NULL,
  `age_ani` INT(3) NOT NULL,
  `date_entree_ani` DATE NOT NULL,
  `date_adoption` DATE NULL,
  `race_ani` TEXT(40) NULL,
  `espece_ani` TEXT(40) NOT NULL,
  `Adoptant_id_adoptant` INT NULL,
  `Refuge_id_refuge` INT NOT NULL,
  PRIMARY KEY (`id_animal`),
  INDEX `fk_Animal_Adoptant_idx` (`Adoptant_id_adoptant` ASC),
  INDEX `fk_Animal_Refuge1_idx` (`Refuge_id_refuge` ASC),
  CONSTRAINT `fk_Animal_Adoptant`
    FOREIGN KEY (`Adoptant_id_adoptant`)
    REFERENCES `ProjetS2`.`Adoptant` (`id_adoptant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_Refuge1`
    FOREIGN KEY (`Refuge_id_refuge`)
    REFERENCES `ProjetS2`.`Refuge` (`id_refuge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetS2`.`Membre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetS2`.`Membre` (
  `id_mb` INT NOT NULL AUTO_INCREMENT,
  `nom_mb` TEXT(50) NOT NULL,
  `prenom_mb` TEXT(40) NOT NULL,
  `fonction_mb` VARCHAR(50) NOT NULL,
  `ville_mb` TEXT(50) NOT NULL,
  `codepost_mb` INT(5) NOT NULL,
  `numrue_mb` VARCHAR(10) NULL,
  `rue_mb` VARCHAR(50) NOT NULL,
  `complad_mb` VARCHAR(40) NULL,
  `age_mb` INT(3) NOT NULL,
  `tel_mb` VARCHAR(14) NOT NULL,
  `Refuge_id_refuge` INT NOT NULL,
  PRIMARY KEY (`id_mb`, `Refuge_id_refuge`),
  INDEX `fk_Membre_Refuge1_idx` (`Refuge_id_refuge` ASC),
  CONSTRAINT `fk_Membre_Refuge1`
    FOREIGN KEY (`Refuge_id_refuge`)
    REFERENCES `ProjetS2`.`Refuge` (`id_refuge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetS2`.`Fournisseur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetS2`.`Fournisseur` (
  `id_four` INT NOT NULL AUTO_INCREMENT,
  `nom_four` VARCHAR(50) NOT NULL,
  `ville_four` TEXT(50) NOT NULL,
  `codepost_four` INT(5) NOT NULL,
  `numrue_four` VARCHAR(10) NULL,
  `rue_four` VARCHAR(50) NOT NULL,
  `complad_four` VARCHAR(40) NULL,
  `tel_four` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_four`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetS2`.`Fourniture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetS2`.`Fourniture` (
  `id_fourni` INT NOT NULL AUTO_INCREMENT,
  `nom_fourni` VARCHAR(60) NOT NULL,
  `type_fourni` VARCHAR(60) NOT NULL,
  `prix_fourni` FLOAT(10) NULL,
  `Fournisseur_id_four` INT NOT NULL,
  PRIMARY KEY (`id_fourni`, `Fournisseur_id_four`),
  INDEX `fk_Fourniture_Fournisseur1_idx` (`Fournisseur_id_four` ASC),
  CONSTRAINT `fk_Fourniture_Fournisseur1`
    FOREIGN KEY (`Fournisseur_id_four`)
    REFERENCES `ProjetS2`.`Fournisseur` (`id_four`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProjetS2`.`Fournisseur_has_Refuge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProjetS2`.`Fournisseur_has_Refuge` (
  `Fournisseur_id_four` INT NOT NULL,
  `Refuge_id_refuge` INT NOT NULL,
  PRIMARY KEY (`Fournisseur_id_four`, `Refuge_id_refuge`),
  INDEX `fk_Fournisseur_has_Refuge_Refuge1_idx` (`Refuge_id_refuge` ASC),
  INDEX `fk_Fournisseur_has_Refuge_Fournisseur1_idx` (`Fournisseur_id_four` ASC),
  CONSTRAINT `fk_Fournisseur_has_Refuge_Fournisseur1`
    FOREIGN KEY (`Fournisseur_id_four`)
    REFERENCES `ProjetS2`.`Fournisseur` (`id_four`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fournisseur_has_Refuge_Refuge1`
    FOREIGN KEY (`Refuge_id_refuge`)
    REFERENCES `ProjetS2`.`Refuge` (`id_refuge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
